require "active_support/core_ext/integer/time"

Rails.application.configure do
  smtp_credentials = Rails.application.credentials[:smtp] || {}
  app_host = ENV["APP_HOST"].presence || Rails.application.credentials.dig(:app, :host).presence || "localhost:3000"

  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store
  config.session_store :cache_store, key: "_stockflow_session"

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = true

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  if app_host.include?(":")
    host, port = app_host.split(":", 2)
    config.action_mailer.default_url_options = { host:, port: port.to_i }
  else
    config.action_mailer.default_url_options = { host: app_host }
  end

  smtp_address = ENV["SMTP_ADDRESS"].presence || smtp_credentials[:address].presence
  config.action_mailer.delivery_method = smtp_address.present? ? :smtp : :file
  config.action_mailer.perform_deliveries = true
  config.action_mailer.file_settings = { location: Rails.root.join("tmp", "mails") }
  config.action_mailer.smtp_settings = {
    user_name: ENV["SMTP_USERNAME"].presence || smtp_credentials[:username].presence,
    password: ENV["SMTP_PASSWORD"].presence || smtp_credentials[:password].presence,
    address: smtp_address || "localhost",
    port: (ENV["SMTP_PORT"].presence || smtp_credentials[:port].presence || 587).to_i,
    domain: ENV["SMTP_DOMAIN"].presence || smtp_credentials[:domain].presence,
    authentication: (ENV["SMTP_AUTHENTICATION"].presence || smtp_credentials[:authentication].presence || "login").to_sym,
    enable_starttls_auto: ActiveModel::Type::Boolean.new.cast(
      ENV["SMTP_ENABLE_STARTTLS_AUTO"].presence || smtp_credentials.fetch(:enable_starttls_auto, true)
    )
  }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
